# Generated by Django 5.0.1 on 2024-01-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_nome_remove_customuser_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
