# Generated by Django 5.0.1 on 2024-01-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='first login'),
        ),
    ]
