# Generated by Django 5.0.1 on 2024-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='largura_barra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
