# Generated by Django 5.0.1 on 2024-01-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_customuser_elapsed_time_customuser_largura_barra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
    ]
