# Generated by Django 5.0.1 on 2024-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_customuser_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=50000000, null=True),
        ),
    ]
