# Generated by Django 5.0.1 on 2024-01-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_customuser_last_saque_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_saque_time',
        ),
    ]
